CREATE OR REPLACE PROCEDURE APT_COUNT
(CNT OUT INT) 
IS
BEGIN
    SELECT COUNT(*) INTO CNT FROM APPOINTMENT_20BRS1193 WHERE INSTR(Appointment_date, 'JUN') > 0 AND Appt_time_hrs >= 12;
END APT_COUNT;
/
