CREATE OR REPLACE PROCEDURE EMPLOYEE_EXIST(NAME_IN IN VARCHAR2, CODE OUT VARCHAR2)
IS 
    E_ID INTEGER;
BEGIN
    SELECT ID INTO E_ID FROM EMP WHERE NAME = NAME_IN;
    CODE := NAME_IN || ' was found in the database.';
EXCEPTION
WHEN NO_DATA_FOUND THEN
    CODE := NAME_IN || ' is not present in the database.';
END EMPLOYEE_EXIST;
/