CREATE OR REPLACE FUNCTION COURSE_DESC
(COURSE_NO COURSES.ID%TYPE)
RETURN VARCHAR2
IS 
C_DESCRIPTION VARCHAR2(200);
BEGIN
    SELECT DESCRIPTION INTO C_DESCRIPTION FROM COURSES WHERE ID = COURSE_NO;
RETURN C_DESCRIPTION;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RETURN('The Course is not in the database');
END COURSE_DESC;
/