set serverout on;
DECLARE
    CURSOR C1 IS SELECT ID, NAME, ADDRESS FROM CUSTOMERS_20BRS1193;
    CUST_ID CUSTOMERS_20BRS1193.ID%TYPE;
    CUST_NAME CUSTOMERS_20BRS1193.NAME%TYPE;
    CUST_ADDRESS  CUSTOMERS_20BRS1193.ADDRESS%TYPE;
BEGIN
    OPEN C1;
        LOOP
            FETCH C1 INTO CUST_ID, CUST_NAME, CUST_ADDRESS;
            EXIT WHEN C1%NOTFOUND;
            dbms_output.put_line(CUST_ID || ' ' || CUST_NAME || ' ' || CUST_ADDRESS);
        END LOOP;
    CLOSE C1;
END;
/